name: rankme-reprod-cpu
channels:
  - conda-forge
  - pytorch
dependencies:
  - python
  - scipy
  - numpy
  - matplotlib
  - pandas
  - pyyaml
  - tqdm
  - make
  - pip
  - pytorch>=2
  - torchvision
  - tensorboard
  - cpuonly
  - mlflow
